INCLUDE globals.ink
INCLUDE prologue/act0_01_birthday.ink
INCLUDE prologue/act0_02_morgue.ink
INCLUDE prologue/act1_01_first_meet.ink
INCLUDE prologue/act1_02_range.ink
INCLUDE prologue/act1_03_blackout.ink
INCLUDE prologue/act1_04_graduation.ink
INCLUDE prologue/act2_01_first_case.ink
INCLUDE prologue/act2_02_wedding.ink
INCLUDE prologue/act2_03_crack.ink
INCLUDE prologue/act2_04_father_case.ink
INCLUDE prologue/act2_05_zhaokai_father.ink
INCLUDE prologue/act2_06_fall.ink
INCLUDE prologue/act3_01_mission.ink
INCLUDE prologue/act3_02_last_dinner.ink
INCLUDE prologue/act3_03_undercover.ink
INCLUDE prologue/act3_03b_crossroads.ink
INCLUDE prologue/act3_04_arrest.ink
INCLUDE mainline/chapters/ch00_container.ink
INCLUDE mainline/chapters/ch01_chamber.ink
INCLUDE mainline/chapters/ch02_pistol.ink
INCLUDE mainline/chapters/ch03_shotgun.ink
INCLUDE mainline/chapters/ch04_twist.ink
INCLUDE mainline/chapters/ch05_sniper.ink
INCLUDE mainline/chapters/ch06_finale.ink
INCLUDE mainline/endings/end01_sakura.ink
INCLUDE mainline/endings/end02_trash_hero.ink
INCLUDE mainline/endings/end03_moon.ink
INCLUDE mainline/endings/end04_ember.ink
INCLUDE mainline/endings/end05_twenty_years.ink
INCLUDE mainline/endings/end06_abyss.ink
INCLUDE mainline/endings/end_true_ferryman.ink
INCLUDE mainline/endings/bad/end_bad01_useless.ink
INCLUDE mainline/endings/bad/end_bad02_blunt.ink
INCLUDE mainline/endings/bad/end_bad03_dismember.ink
INCLUDE mainline/endings/bad/end_bad04_dawnDoor.ink
INCLUDE mainline/endings/bad/end_bad05_fatalPoint.ink
INCLUDE mainline/endings/bad/end_bad06_abyss_end.ink
INCLUDE mainline/endings/bad/end_bad07_escape.ink
INCLUDE betrayal/chapters/ch_a01_initiation.ink
INCLUDE betrayal/chapters/ch_a02_dock.ink
INCLUDE betrayal/chapters/ch_a03_diary.ink
INCLUDE betrayal/chapters/ch_a04_finale.ink
INCLUDE betrayal/endings/end_a01_ferry.ink
INCLUDE betrayal/endings/end_a02_sinking.ink
INCLUDE betrayal/endings/end_a03_broken_anchor.ink
INCLUDE betrayal/endings/end_a04_echo.ink
INCLUDE newgame_plus/ngp_new_content.ink

{ week == 2: -> ngp_new_content }
-> act0_01_birthday
